package modelo;
// Generated 26/11/2021 13:09:34 by Hibernate Tools 4.3.1


import java.util.Date;

import java.util.List;


/**
 * Alquiler generated by hbm2java
 */
public class Alquiler  extends Contrato implements java.io.Serializable {

     private Long dnigarante;
     private List<Servicio> servicios;
    public Alquiler() {
    }
	
    
    public Alquiler(Long id, Double recargofijo, Double valorbaserecargo, Date iniciocontrato, Date fincontrato, Long idinmueble, Long dnilocatario, Long dnilocador, Double montocomision, List<Arancel> arancels, Integer cantaranceles, List<Servicio> servicios, Long dnigarante, Integer tipocontrato) {
        super(id, recargofijo, valorbaserecargo, iniciocontrato, fincontrato, idinmueble, dnilocatario, dnilocador, montocomision, arancels, cantaranceles, tipocontrato);
        this.dnigarante = dnigarante;
        this.servicios = servicios;
    }

    public Long getDnigarante() {
        return dnigarante;
    }

    public void setDnigarante(Long dnigarante) {
        this.dnigarante = dnigarante;
    }

    public List<Servicio> getServicios() {
        return servicios;
    }

    public void setServicios(List<Servicio> servicios) {
        this.servicios = servicios;
    }

    




}


