package modelo;
// Generated 26/11/2021 13:09:34 by Hibernate Tools 4.3.1

import java.util.Date;



// Generated 26/11/2021 13:09:34 by Hibernate Tools 4.3.1



/**
 * Arancel generated by hbm2java
 */
public class Arancel  implements java.io.Serializable {


     private long idarancel;
     private long idcontrato;
     private Integer diasmora;
     private Boolean pagado;
     private Double montoarancel;
     private Double montosegunda;
     private Date primerfecha;
     private Date segundafecha;

    public Arancel() {
    }

    /**
     *
     * @param idarancel
     * @param idcontrato
     * @param diasmora
     * @param pagado
     * @param montoarancel
     * @param montosegunda
     * @param primerfecha
     * @param segundafecha
     */
    public Arancel(long idarancel,long idcontrato, Integer diasmora, Boolean pagado, Double montoarancel, Double montosegunda, Date primerfecha, Date segundafecha) {
       this.idarancel = idarancel;
       this.idcontrato = idcontrato;
       this.diasmora = diasmora;
       this.pagado = pagado;
       this.montoarancel = montoarancel;
       this.montosegunda = montosegunda;
       this.primerfecha = primerfecha;
       this.segundafecha = segundafecha;
    }
   
    public long getIdarancel() {
        return this.idarancel;
    }
    
    public void setIdarancel(long idarancel) {
        this.idarancel = idarancel;
    }

    public long getIdcontrato() {
        return idcontrato;
    }

    public void setIdcontrato(long idcontrato) {
        this.idcontrato = idcontrato;
    }
    
    public Integer getDiasmora() {
        return this.diasmora;
    }
    
    public void setDiasmora(Integer diasmora) {
        this.diasmora = diasmora;
    }
    public Boolean getPagado() {
        return this.pagado;
    }
    
    public void setPagado(Boolean pagado) {
        this.pagado = pagado;
    }
    public Double getMontoarancel() {
        return this.montoarancel;
    }
    
    public void setMontoarancel(Double montoarancel) {
        this.montoarancel = montoarancel;
    }

    public Double getMontosegunda() {
        return montosegunda;
    }

    public void setMontosegunda(Double montosegunda) {
        this.montosegunda = montosegunda;
    }
    

    public Date getPrimerfecha() {
        return primerfecha;
    }

    public void setPrimerfecha(Date primerfecha) {
        this.primerfecha = primerfecha;
    }

    public Date getSegundafecha() {
        return segundafecha;
    }

    public void setSegundafecha(Date segundafecha) {
        this.segundafecha = segundafecha;
    }

    @Override
    public String toString() {
        return "Arancel{" + "idarancel=" + idarancel + ", diasmora=" + diasmora + ", pagado=" + pagado + ", montoarancel=" + montoarancel + ", montosegunda=" + montosegunda + ", primerfecha=" + primerfecha + ", segundafecha=" + segundafecha + '}';
    }

}


