package modelo;
// Generated 26/11/2021 13:09:34 by Hibernate Tools 4.3.1

// Generated 26/11/2021 13:09:34 by Hibernate Tools 4.3.1



/**
 * Casa generated by hbm2java
 */
public class Casa  extends Propiedad implements java.io.Serializable {


    public Casa(){}

	
    public Casa(long id, String ubicacion, String tamano, String localidad, Integer cantidadhabitaciones, Integer cantidadbanos, Boolean cochera, int tipo) {
       super(id, ubicacion, tamano, localidad, cantidadhabitaciones, cantidadbanos, cochera, tipo);
    }
   



}


