package modelo;
// Generated 26/11/2021 13:09:34 by Hibernate Tools 4.3.1



import java.util.Date;

import java.util.List;



/**
 * Contrato generated by hbm2java
 */

public class Contrato  implements java.io.Serializable {

    
     private Long id;
     private Double recargofijo;
     private Double valorbaserecargo;
     private Date iniciocontrato;
     private Date fincontrato;
     private Long idinmueble;
     private Long dnilocatario;
     private Long dnilocador;
     private Double montocomision;
     private List <Arancel> arancels;
     private Integer cantaranceles;
     private int tipocontrato;
     
    public Contrato(){}

	
    public Contrato(long id) {
        this.id = id;
    }
    public Contrato(Long id, Double recargofijo, Double valorbaserecargo, Date iniciocontrato, Date fincontrato, Long idinmueble, Long dnilocatario, Long dnilocador, Double montocomision, List<Arancel> arancels, Integer cantaranceles, Integer tipocontrato) {
       this.id = id;
       this.recargofijo = recargofijo;
       this.valorbaserecargo = valorbaserecargo;
       this.iniciocontrato = iniciocontrato;
       this.fincontrato = fincontrato;
       this.idinmueble = idinmueble;
       this.dnilocatario = dnilocatario;
       this.dnilocador = dnilocador;
       this.montocomision = montocomision;
       this.cantaranceles = cantaranceles;
       this.arancels = arancels;
       this.tipocontrato = tipocontrato;

    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public Double getRecargofijo() {
        return recargofijo;
    }

    public void setRecargofijo(Double recargofijo) {
        this.recargofijo = recargofijo;
    }

    public Double getValorbaserecargo() {
        return valorbaserecargo;
    }

    public void setValorbaserecargo(Double valorbaserecargo) {
        this.valorbaserecargo = valorbaserecargo;
    }

    public Double getMontocomision() {
        return montocomision;
    }

    public void setMontocomision(Double montocomision) {
        this.montocomision = montocomision;
    }
    
    public void setIniciocontrato(Date iniciocontrato) {
        this.iniciocontrato = iniciocontrato;
    }

    public Date getIniciocontrato() {
        return iniciocontrato;
    }
    public Date getFincontrato() {
        return this.fincontrato;
    }
    
    public void setFincontrato(Date fincontrato) {
        this.fincontrato = fincontrato;
    }

    public Long getDnilocatario() {
        return dnilocatario;
    }

    public void setDnilocatario(Long dnilocatario) {
        this.dnilocatario = dnilocatario;
    }

    public Long getDnilocador() {
        return dnilocador;
    }

    public void setDnilocador(Long dnilocador) {
        this.dnilocador = dnilocador;
    }

    public Long getIdinmueble() {
        return idinmueble;
    }

    public void setIdinmueble(Long idinmueble) {
        this.idinmueble = idinmueble;
    }


    public List<Arancel> getArancels() {
        return arancels;
    }

    public void setArancels(List<Arancel> arancels) {
        this.arancels = arancels;
    }

    public Integer getTipocontrato() {
        return tipocontrato;
    }

    public void setTipocontrato(Integer tipocontrato) {
        this.tipocontrato = tipocontrato;
    }

    public Integer getCantaranceles() {
        return cantaranceles;
    }

    public void setCantaranceles(Integer cantaranceles) {
        this.cantaranceles = cantaranceles;
    }

    @Override
    public String toString() {
        return "Contrato{" + "id=" + id + ", recargofijo=" + recargofijo + ", valorbaserecargo=" + valorbaserecargo + ", iniciocontrato=" + iniciocontrato + ", fincontrato=" + fincontrato + ", idinmueble=" + idinmueble + ", dnilocatario=" + dnilocatario + ", dnilocador=" + dnilocador + ", montocomision=" + montocomision + ", arancels=" + arancels + ", cantaranceles=" + cantaranceles + ", tipocontrato=" + tipocontrato + '}';
    }
   



}


