package modelo;
// Generated 26/11/2021 13:09:34 by Hibernate Tools 4.3.1


// Generated 26/11/2021 13:09:34 by Hibernate Tools 4.3.1



/**
 * Garante generated by hbm2java
 */
public class Garante  extends Persona implements java.io.Serializable {


     private String actividaddedicada;
     private Double ingresos;
    public Garante() {
    }

	
   
    public Garante(long dni, String nombre, String estadocivil, String domicilio, String telefono, String mail, String actividaddedicada, int tipo, Double ingresos) {
       super(dni, nombre, estadocivil, domicilio, telefono, mail, tipo);
       this.actividaddedicada = actividaddedicada;
       this.ingresos = ingresos;
    }
   
    
    public String getActividaddedicada() {
        return this.actividaddedicada;
    }
    
    public void setActividaddedicada(String actividaddedicada) {
        this.actividaddedicada = actividaddedicada;
    }

    public Double getIngresos() {
        return ingresos;
    }

    public void setIngresos(Double ingresos) {
        this.ingresos = ingresos;
    }




}


