package modelo;
// Generated 26/11/2021 13:09:34 by Hibernate Tools 4.3.1


// Generated 26/11/2021 13:09:34 by Hibernate Tools 4.3.1



/**
 * Inmueble generated by hbm2java
 */
public class Inmueble  implements java.io.Serializable {


     private long id;
     private String ubicacion;
     private String tamano;
     private String localidad;
     private int tipo;

    public Inmueble() {
    }

	
    public Inmueble(long id, String ubicacion, String tamano, String localidad, int tipo) {
       this.id = id;
       this.ubicacion = ubicacion;
       this.tamano = tamano;
       this.localidad = localidad;
       this.tipo = tipo;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
    }
    public String getTamano() {
        return this.tamano;
    }
    
    public void setTamano(String tamano) {
        this.tamano = tamano;
    }
    public String getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }

    public int getTipo() {
        return tipo;
    }

    public void setTipo(int tipo) {
        this.tipo = tipo;
    }
    

}


