package modelo;
// Generated 26/11/2021 13:09:34 by Hibernate Tools 4.3.1


// Generated 26/11/2021 13:09:34 by Hibernate Tools 4.3.1



/**
 * Locatario generated by hbm2java
 */
public class Locatario  extends Persona implements java.io.Serializable {



     private String actividaddedicada;
     private Boolean estudiante;
     private Double ingresos;
     private String usuario;
     private String contrasena;

    public Locatario() {
    }

	
    
    public Locatario(long dni, String nombre, String estadocivil, String domicilio, String telefono, String mail, String actividaddedicada, Boolean estudiante, Double ingresos, String usuario, String contrasena, int tipo) {
       super(dni, nombre, estadocivil, domicilio, telefono, mail, tipo);
       this.actividaddedicada = actividaddedicada;
       this.estudiante = estudiante;
       this.ingresos = ingresos;
       this.usuario = usuario;
       this.contrasena = contrasena;
    }
   
    
    
    public String getActividaddedicada() {
        return this.actividaddedicada;
    }
    
    public void setActividaddedicada(String actividaddedicada) {
        this.actividaddedicada = actividaddedicada;
    }
    public Boolean getEstudiante() {
        return this.estudiante;
    }
    
    public void setEstudiante(Boolean estudiante) {
        this.estudiante = estudiante;
    }
    public Double getIngresos() {
        return this.ingresos;
    }
    
    public void setIngresos(Double ingresos) {
        this.ingresos = ingresos;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }




}


