package modelo;
// Generated 26/11/2021 13:09:34 by Hibernate Tools 4.3.1


// Generated 26/11/2021 13:09:34 by Hibernate Tools 4.3.1



/**
 * Locador generated by hbm2java
 */
public class Locador extends Persona implements java.io.Serializable {



    public Locador() {
    }

	
    
    public Locador(long dni, String nombre, String estadocivil, String domicilio, String telefono, String mail, int tipo) {
       super(dni, nombre, estadocivil, domicilio, telefono, mail, tipo);
    }


   
    




}


