package modelo;
// Generated 26/11/2021 13:09:34 by Hibernate Tools 4.3.1


// Generated 26/11/2021 13:09:34 by Hibernate Tools 4.3.1



/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private long dni;
     private String nombre;
     private String estadocivil;
     private String domicilio;
     private String telefono;
     private String mail;
     private int tipo;

    public Persona() {
    }

	
    public Persona(long dni) {
        this.dni = dni;
    }
    public Persona(long dni, String nombre, String estadocivil, String domicilio, String telefono, String mail, int tipo) {
       this.dni = dni;
       this.nombre = nombre;
       this.estadocivil = estadocivil;
       this.domicilio = domicilio;
       this.telefono = telefono;
       this.mail = mail;
       this.tipo = tipo;
    }
   
    public long getDni() {
        return this.dni;
    }
    
    public void setDni(long dni) {
        this.dni = dni;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getEstadocivil() {
        return this.estadocivil;
    }
    
    public void setEstadocivil(String estadocivil) {
        this.estadocivil = estadocivil;
    }
    public String getDomicilio() {
        return this.domicilio;
    }
    
    public void setDomicilio(String domicilio) {
        this.domicilio = domicilio;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }

    public int getTipo() {
        return tipo;
    }

    public void setTipo(int tipo) {
        this.tipo = tipo;
    }


}


