package modelo;
// Generated 26/11/2021 13:09:34 by Hibernate Tools 4.3.1


// Generated 26/11/2021 13:09:34 by Hibernate Tools 4.3.1

/**
 * Servicio generated by hbm2java
 */
public class Servicio  implements java.io.Serializable {


     private long id;
     private String tiposervicio;
     private Double monto;

    public Servicio() {
    }

	
    public Servicio(long id, String tiposervicio, Double monto) {
       this.id = id;
       this.tiposervicio = tiposervicio;
       this.monto = monto;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    
    public String getTiposervicio() {
        return this.tiposervicio;
    }
    
    public void setTiposervicio(String tiposervicio) {
        this.tiposervicio = tiposervicio;
    }
    public Double getMonto() {
        return this.monto;
    }
    
    public void setMonto(Double monto) {
        this.monto = monto;
    }

    @Override
    public String toString() {
        return "Servicio{" + "id=" + id + ", tiposervicio=" + tiposervicio + ", monto=" + monto + '}';
    }




}


