package modelo;
// Generated 26/11/2021 13:09:34 by Hibernate Tools 4.3.1


// Generated 26/11/2021 13:09:34 by Hibernate Tools 4.3.1



/**
 * Terreno generated by hbm2java
 */
public class Terreno  extends Inmueble implements java.io.Serializable {

    public Terreno() {
    }

    public Terreno(long id, String ubicacion, String tamano, String localidad, int tipo) {
       super(id, ubicacion, tamano, localidad, tipo);
    }
  




}


