package modelo;
// Generated 26/11/2021 13:09:34 by Hibernate Tools 4.3.1


// Generated 26/11/2021 13:09:34 by Hibernate Tools 4.3.1



/**
 * Tipotrabajador generated by hbm2java
 */
public class Tipotrabajador  implements java.io.Serializable {


     private long id;
     private int tipo;
     
    public Tipotrabajador() {
    }

    public Tipotrabajador(long id, int tipo) {
        this.id = id;
        this.tipo = tipo;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public int getTipo() {
        return tipo;
    }

    public void setTipo(int tipo) {
        this.tipo = tipo;
    }





}


